package com.idp.universalremote.domain.model

enum class RemoteKey {
    POWER, HOME, BACK, MENU, EXIT, GUIDE, INFO, TOOLS, SOURCE,
    UP, DOWN, LEFT, RIGHT, OK,
    VOL_UP, VOL_DOWN, MUTE,
    CH_UP, CH_DOWN, PRE_CH, TTX,
    NUM_0, NUM_1, NUM_2, NUM_3, NUM_4, NUM_5, NUM_6, NUM_7, NUM_8, NUM_9,
    PLAY, PAUSE, PLAY_PAUSE, STOP, REWIND, FORWARD, NEXT, PREVIOUS,
    RED, GREEN, YELLOW, BLUE,
    KEYBOARD, VOICE,
    OPTIONS, INSTANT_REPLAY, BACKSPACE,
    APP_NETFLIX, APP_YOUTUBE, APP_PRIME, APP_DISNEY, APP_SPOTIFY, APP_HBO,
    APP_HULU, APP_APPLE_TV, APP_PLEX, APP_PARAMOUNT, APP_PEACOCK, APP_TUBI, APP_PLUTO
}
